### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mdaines** [bpartridge/graphviz.js#2]
I am using parts of this project in my own Emscripten build of Graphviz: (mainly the find_emscripten.py script)

https://github.com/mdaines/viz.js

I wanted to know if it would be okay for me to continue doing so. Do you plan on applying an open-source license to your work? Or, may I have your permission to use the work you've done?

**Comment by bpartridge** [comment]
Sorry I never responded to you! (I was browsing some older repositories of mine, and found this.) If it's still relevant, I'm placing my original content in this repository (makefiles, etc.) under the public domain (so you can use them under any license you'd like). I would greatly appreciate a mention in the viz.js readme if you're still using the components, but I see no reason to add any legal constraints! Thanks for your interest, and hope viz.js is going well!
